version: '2.4'
# networks:
#   bridge:
#     external: true
services:
  dm:
    image: cds
    container_name: dm
    volumes:
      - ../../cmd/dm/cmd/sync/etc/dm.json:/cds/dm/cmd/sync/etc/dm.json
    command:
       /cds/build/dm -f /cds/dm/cmd/sync/etc/dm.json
  galaxy:
    image: cds
    container_name: galaxy
    restart: always
    ports:
      - "8080:8080" # for debuging
    volumes:
      - ../../cmd/galaxy/etc/galaxy-api.yaml:/cds/galaxy/etc/galaxy-api.yaml
    working_dir: /cds/galaxy
    command:
      /cds/build/galaxy -f /cds/galaxy/etc/galaxy-api.yaml
  rtu:
    image: cds
    container_name: rtu
    volumes:
      - ../../cmd/rtu/conf.json:/cds/rtu/conf.json
    command:
      /cds/build/rtu -f /cds/rtu/conf.json
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - 3414:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/:/var/log/nginx
      - ../../web/dist:/usr/local/html
    depends_on:
      - galaxy
      - rtu
      - dm 